# Utiliser une image de base Java
FROM openjdk:11-jre-slim

# Créer un répertoire pour l'application
WORKDIR /app

# Copier le fichier JAR dans le conteneur
COPY gestion-station-ski.jar app.jar

# Exposer le port de l'application
EXPOSE 8089

# Commande pour exécuter l'application
CMD ["java", "-jar", "app.jar"]
